=== efwoods/XML_Udemy_Practice/SimpleTypesAssignment/order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/order"
	xmlns:tns="http://www.example.org/order" elementFormDefault="qualified">
	
	<element name="order" type="tns:order"/>
	<complexType name="order">
		<sequence>
			<element name="customer" type="tns:customer"/>
			<element name="product" type="tns:product" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="id" type="tns:idRestriction" use="required"/>
	</complexType>
	
	<complexType name="customer">
		<sequence>
			<element name="name" type="string"/>
			<element name="phone" type="string" minOccurs="0"/>	
		</sequence>
		<attribute name="id" type="int" use="required"/>
	</complexType>
	
	<complexType name="product">
		<sequence>
			<element name="name" type="tns:nameLength"/>
			<element name="description" type="tns:descriptionLength"/>
			<element name="price" type="int"/>
			<element name="category" type="tns:categories"/>	
		</sequence>
		
		<attribute name="id" type="int" use="required"/>
	</complexType>
	
	
	
	<simpleType name="nameLength">
		<restriction base="string">
			<maxLength value="20"/>
		</restriction>
	</simpleType>
	
	<simpleType name="descriptionLength">
		<restriction base="string">
			<maxLength value="100"/>
		</restriction>
	</simpleType>
	
	<simpleType name="categories">
		<restriction base="string">
			<enumeration value="electronics"/>
			<enumeration value="books"/>
			<enumeration value="shoes"/>
		</restriction>
	</simpleType>
	
	<simpleType name="idRestriction">
		<restriction base="int">
			<maxInclusive value="50"/>
		</restriction>
	</simpleType>
</schema>

=== efwoods/XML_Udemy_Practice/SimpleTypesAssignment/order.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:order id="50" xmlns:tns="http://www.example.org/order" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/order order.xsd ">
  <tns:customer id="0">
    <tns:name>tns:name</tns:name>
  </tns:customer>
  <tns:product id="50">
    <tns:name>tns:name</tns:name>
    <tns:description>tns:description</tns:description>
    <tns:price>0</tns:price>
    <tns:category>electronics</tns:category>
  </tns:product>
</tns:order>
